name: Windows_RDP_Pankaj
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: User Setup
        run: |
          net user AdminPankaj Pankaj@123 /add
          net localgroup administrators AdminPankaj /add
          
      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
          Start-Process -FilePath .\tailscale.exe -ArgumentList "/quiet" -Wait
          
      - name: Connect Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey 'tskey-auth-kop8h9f5dz11CNTRL-V6pfdWmQcM5pHsQSkSh9N5tn2uNeUiBH'
          
      - name: Keep Alive (Max Limit)
        run: |
          Write-Host "RDP chalu hai! Note: GitHub free tier restricts jobs to 6 hours."
          # 21600 seconds = 6 hours (GitHub's hard limit)
          Start-Sleep -Seconds 21600
