name: Windows_RDP_Pankaj
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: User Setup
        run: |
          net user AdminPankaj Pankaj@123 /add
          net localgroup administrators AdminPankaj /add
          
      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
          Start-Process -FilePath .\tailscale.exe -ArgumentList "/quiet" -Wait
          
      - name: Connect Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey 'tskey-auth-kNjtSXqGus11CNTRL-5SXkdpSnjyWvzznyEHLByWYu9ekdcDS7L'
          
      - name: Keep Alive (Max Limit)
        run: |
          Write-Host "RDP Active hai! 1920x1080 setup karein."
          # GitHub Free tier limit 6 hours hai
          Start-Sleep -Seconds 21600
