name: Windows_RDP_Pankaj
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: User Setup
        run: |
          net user AdminPankaj Pankaj@123 /add
          net localgroup administrators AdminPankaj /add
          
      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
          Start-Process -FilePath .\tailscale.exe -ArgumentList "/quiet" -Wait
          
      - name: Connect Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey 'tskey-auth-kJjEjhhHzA21CNTRL-RDBC4opTL3J8UbWTKGFy3JUY6gshSGRf'
          
      - name: Keep Alive (Attempting 24 Hours)
        run: |
          Write-Host "RDP Active! 1920x1080 Streaming ke liye OBS setup karein."
          # 86400 seconds = 24 hours (Note: GitHub might kill this at 6 hours)
          Start-Sleep -Seconds 86400
