name: Windows_RDP_Pankaj
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: User Setup
        run: |
          net user AdminPankaj Pankaj@123 /add
          net localgroup administrators AdminPankaj /add
          
      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale.exe
          Start-Process -FilePath .\tailscale.exe -ArgumentList "/quiet" -Wait
          
      - name: Connect Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey 'tskey-auth-kQRpc9EcTv11CNTRL-wnbRLBx8azQSPK4o4nRwyQwVKGcmtEaXR'
          
      - name: Keep Alive (Max Limit)
        run: |
          Write-Host "RDP Active hai! OBS mein 1920x1080 resolution manually type karein."
          # GitHub Free tier limit 6 hours (21600 seconds) hai
          Start-Sleep -Seconds 21600
